### ISSUE TITLE
Uwagi

### ISSUE THREAD

**Issue by agudys** [mjakobczyk/minhash#1]
[wymagania-do-pracy-inżynierskiej.pdf](https://github.com/mjakobczyk/minhash/files/2463471/wymagania-do-pracy-inzynierskiej.pdf)
1. Usunięcie zależności od Boost.
2. Na wejściu i wyjściu tablica int64_t.
3. Eksperymenty czasowe.
4. Eksperyment jakościowy (błąd oszacowania podobieństwa w zależności od progu odcięcia).
5. Wyrównać adresy w pamięci operacyjnej. 
6. Minhash jako oddzielna biblioteka statyczna.

**Comment by agudys** [comment]
A tutaj ma Pan pliki do ustalenia dostępnych rozszerzeń CPU.

[src.zip](https://github.com/mjakobczyk/minhash/files/2463865/src.zip)

**Comment by mjakobczyk** [comment]
All the necessary updates has been made. Closing.
